Added back in some missing header information for this script.

diff --git a/bin/makeIndexes b/bin/makeIndexes
--- a/bin/makeIndexes
+++ b/bin/makeIndexes
@@ -1,5 +1,16 @@
 #!/bin/sh
 
+cd `dirname $0`
+
+INDEX_CONFIG=../searchtool_indexer.config
+
+if [ ! -r ${INDEX_CONFIG} ]
+then
+    echo "Cannot read configuration file: ${INDEX_CONFIG}" | tee -a ${LOG}
+    exit 1
+fi
+. ${INDEX_CONFIG}
+
 # Create the Marker and Vocab Related Indexes
 
 makeMarkersAndVocab
